name: Tests
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: go test
      run: go test -coverprofile cover.out -v ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
